apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-bb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-bb
  template:
    metadata:
      labels:
        app: frontend-bb
    spec:
      containers:
        - name: frontend-bb
          image: navdeep650/frontend_ticket
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-bb-service
spec:
  type: NodePort
  selector:
    app: frontend-bb
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32283
